apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: wentask

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: ismak07/wentask-backend:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret